import type { MemoryStatusSnapshot } from '../../types/memory.js';

export function createUnavailableMemoryStatusSnapshot(
  overrides: Partial<MemoryStatusSnapshot> = {},
): MemoryStatusSnapshot {
  return {
    schemaVersion: 2,
    available: false,
    enabled: false,
    maintenance: false,
    readEnabled: false,
    writeEnabled: false,
    extractConfigured: false,
    embedConfigured: false,
    extractModel: '',
    embedModel: '',
    jobs: {
      pending: 0,
      leased: 0,
      failed: 0,
      deadLetter: 0,
      byType: {
        extract: 0,
        embed: 0,
        backfill: 0,
        maintenance: 0,
      },
    },
    counts: {
      active: 0,
      pendingReview: 0,
      archived: 0,
      retracted: 0,
      forgotten: 0,
      stranded: 0,
      ftsRows: 0,
      embeddingRows: 0,
      orphanEvidence: 0,
      staleFts: 0,
      inactiveFts: 0,
      staleEmbedding: 0,
      inactiveEmbedding: 0,
      strandedByReason: {
        payload: 0,
        evidence: 0,
        audience: 0,
        embedding: 0,
        fts: 0,
      },
    },
    providerRoutes: [],
    lastMaintenanceAt: null,
    extract: {
      configured: false,
      state: 'never',
      lastSource: null,
      lastAttemptAt: null,
      lastSuccessAt: null,
      lastFailureAt: null,
      lastLatencyMs: null,
      lastError: null,
      consecutiveFailures: 0,
    },
    embed: {
      configured: false,
      state: 'never',
      lastSource: null,
      lastAttemptAt: null,
      lastSuccessAt: null,
      lastFailureAt: null,
      lastLatencyMs: null,
      lastError: null,
      consecutiveFailures: 0,
    },
    ...overrides,
  };
}
