import type {
  ToolCatalogEntry,
  ToolRouteProfileInfo,
  ToolScopeTarget,
} from '../../types/tool-policy.js';

export const GLOBAL_DEFAULT_SCOPE_ID = 'global-default';
export const PRIVATE_DEFAULT_SCOPE_ID = 'private-default';

const ALL_ROUTES = ['agent', 'automation'] as const;
const AGENT_ONLY_ROUTES = ['agent'] as const;

type ToolCatalogInput = Omit<
  ToolCatalogEntry,
  'availableRoutes' | 'defaultEnabledByRoute' | 'management' | 'visibility'
> & Partial<Pick<ToolCatalogEntry, 'management' | 'visibility'>>;

function buildCatalogEntry(entry: ToolCatalogInput): ToolCatalogEntry {
  return {
    ...entry,
    management: entry.management ?? 'editable',
    visibility: entry.visibility ?? (entry.pluginId ? 'plugin' : 'standalone'),
    availableRoutes: [...ALL_ROUTES],
    defaultEnabledByRoute: {
      agent: true,
      automation: true,
    },
  };
}

function buildAgentOnlyCatalogEntry(
  entry: ToolCatalogInput,
): ToolCatalogEntry {
  return {
    ...entry,
    management: entry.management ?? 'editable',
    visibility: entry.visibility ?? (entry.pluginId ? 'plugin' : 'standalone'),
    availableRoutes: [...AGENT_ONLY_ROUTES],
    defaultEnabledByRoute: {
      agent: true,
      automation: false,
    },
  };
}

function buildAgentOnlyDisabledCatalogEntry(
  entry: ToolCatalogInput,
): ToolCatalogEntry {
  return {
    ...entry,
    management: entry.management ?? 'editable',
    visibility: entry.visibility ?? (entry.pluginId ? 'plugin' : 'standalone'),
    availableRoutes: [...AGENT_ONLY_ROUTES],
    defaultEnabledByRoute: {
      agent: false,
      automation: false,
    },
  };
}

function buildLockedCatalogEntry(entry: ToolCatalogInput): ToolCatalogEntry {
  return {
    ...buildCatalogEntry({ ...entry, management: 'locked_off' }),
    defaultEnabledByRoute: {
      agent: false,
      automation: false,
    },
  };
}

function buildAgentOnlyLockedCatalogEntry(entry: ToolCatalogInput): ToolCatalogEntry {
  return buildAgentOnlyDisabledCatalogEntry({ ...entry, management: 'locked_off' });
}

export const TOOL_ROUTE_PROFILES: ToolRouteProfileInfo[] = [
  {
    id: 'agent',
    title: 'Agent 回复',
    description: 'qqbot reply 唯一的工具型回复链路。模型可先走原生 tool loop，最后一跳返回 StructuredReply。',
    note: '仅允许 plugin 房间进入。',
  },
  {
    id: 'automation',
    title: '自动化',
    description: '自动化任务到点后启动独立 Agent run，并按这套路由决定可调用工具。',
    note: '创建任务工具只在 agent 路由暴露；自动化 run 使用本路由解析实际工具开关。',
  },
];

export const TOOL_DEFAULT_SCOPES: ToolScopeTarget[] = [
  {
    scopeKind: 'global_default',
    scopeId: GLOBAL_DEFAULT_SCOPE_ID,
    title: '全局默认',
    description: '所有会话的基础默认值。群聊和私聊都先继承这里。',
  },
  {
    scopeKind: 'private_default',
    scopeId: PRIVATE_DEFAULT_SCOPE_ID,
    title: '私聊默认',
    description: '所有私聊会话的默认值。单个私聊房间可继续覆盖。',
  },
];

export interface AgentToolPluginDefinition {
  id: string;
  displayName: string;
  shortDescription: string;
  longDescription: string;
  category: string;
  capabilities: string[];
  toolNames: string[];
  kind: 'workspace' | 'tool-bundle';
  lockedReason?: string;
}

export const AGENT_TOOL_PLUGINS: AgentToolPluginDefinition[] = [
  {
    id: 'workspace',
    displayName: 'Workspace',
    shortDescription: '文件、Shell 与会话附件上下文。',
    longDescription: 'Workspace 管理 Agent 的文件系统、命令执行、附件回放与实时会话上下文能力。',
    category: 'Agent Runtime',
    capabilities: ['Read and edit files', 'Run shell commands', 'Read conversation artifacts'],
    toolNames: [
      'file_read',
      'file_write',
      'file_edit',
      'file_publish',
      'grep',
      'glob',
      'bash',
      'qqbot_attachment_replay',
      'realtime_message_history',
    ],
    kind: 'workspace',
  },
  {
    id: 'automation',
    displayName: 'Automation',
    shortDescription: '创建与管理定时、周期和被动触发任务。',
    longDescription: 'Automation 统一管理 trigger 与现有自动化任务操作；后续 runtime 收敛为单一 trigger 接口。',
    category: 'Agent Workflow',
    capabilities: ['Scheduled tasks', 'Passive triggers'],
    toolNames: [
      'trigger',
      'automation_create',
      'automation_list',
      'automation_update',
      'automation_pause',
      'automation_resume',
      'automation_delete',
    ],
    kind: 'tool-bundle',
  },
  {
    id: 'interaction',
    displayName: 'Interaction',
    shortDescription: '在 Agent 执行期间向用户提问或请求确认。',
    longDescription: '当前 QQBot 回复流程不需要暂停 Agent run 等待交互输入。',
    category: 'Agent Workflow',
    capabilities: ['Structured questions', 'Open-ended confirmation'],
    toolNames: ['question', 'user_confirm'],
    kind: 'tool-bundle',
    lockedReason: '当前机器人场景不使用执行中交互，保持关闭。',
  },
  {
    id: 'hbu-course-guidance',
    displayName: 'HBU Course Guidance',
    shortDescription: '河北大学选课信息与推荐验证。',
    longDescription: '选课能力由确定性的 QQBot 命令链路负责，不进入 Agent tool loop。',
    category: 'Campus Command',
    capabilities: ['Course context', 'Live offerings', 'Recommendation validation'],
    toolNames: [
      'hbu_jw_course_guidance_context',
      'hbu_jw_course_offerings',
      'hbu_jw_validate_course_recommendation',
    ],
    kind: 'tool-bundle',
    lockedReason: '纯命令触发能力，不允许 Agent 调用。',
  },
  {
    id: 'codeforces',
    displayName: 'Codeforces',
    shortDescription: '用户资料、Rating、提交和比赛查询。',
    longDescription: 'Codeforces 正在迁移到确定性的 QQBot 命令链路，Agent tools 保持关闭。',
    category: 'Command Service',
    capabilities: ['Profile cards', 'Rating history', 'Submissions', 'Contests'],
    toolNames: ['cf_user_profile', 'cf_user_rating', 'cf_user_submissions', 'cf_contests'],
    kind: 'tool-bundle',
    lockedReason: '已确定迁移为纯命令触发，Agent 调用保持关闭。',
  },
  {
    id: 'web',
    displayName: 'Web',
    shortDescription: '搜索、网页读取、PDF 截图与天气查询。',
    longDescription: 'Web 通过一个统一工具向 Agent 提供可追溯的网络读取能力。',
    category: 'Agent Runtime',
    capabilities: ['Search', 'Read pages', 'Inspect PDFs'],
    toolNames: ['web_run'],
    kind: 'tool-bundle',
  },
];

export const AGENT_TOOL_PLUGIN_MAP = new Map(
  AGENT_TOOL_PLUGINS.map((plugin) => [plugin.id, plugin]),
);

export const LEGACY_TOOL_NAME_ALIASES: Record<string, string | null> = {
  built_user_toast: null,
  file_update: 'file_edit',
  file_grep: 'grep',
  file_glob: 'glob',
};

export const TOOL_CATALOG: ToolCatalogEntry[] = [
  buildCatalogEntry({
    toolName: 'trigger',
    title: '自动化触发器',
    category: 'builtin',
    description: '统一管理定时、周期和被动触发任务。',
    compatibility: 'compatible',
    compatibilityNote: 'Automation Plugin 的统一 Agent 入口。',
    hardDependencies: [],
    relatedTools: ['automation_create', 'automation_list', 'automation_update', 'automation_pause', 'automation_resume', 'automation_delete'],
    riskLevel: 'medium',
    source: 'chatluna_runtime',
    pluginId: 'automation',
  }),
  buildAgentOnlyLockedCatalogEntry({
    toolName: 'question',
    title: '结构化提问',
    category: 'builtin',
    description: '在 Agent run 中向用户展示选项并等待回答。',
    compatibility: 'incompatible',
    compatibilityNote: '当前 QQBot 回复流程不等待执行中交互。',
    hardDependencies: [],
    relatedTools: ['user_confirm'],
    riskLevel: 'low',
    source: 'chatluna_runtime',
    pluginId: 'interaction',
    managementNote: '当前机器人场景不使用执行中交互，保持关闭。',
  }),
  buildAgentOnlyLockedCatalogEntry({
    toolName: 'user_confirm',
    title: '用户确认',
    category: 'builtin',
    description: '在 Agent run 中等待用户自由输入或确认。',
    compatibility: 'incompatible',
    compatibilityNote: '当前 QQBot 回复流程不等待执行中交互。',
    hardDependencies: [],
    relatedTools: ['question'],
    riskLevel: 'low',
    source: 'chatluna_runtime',
    pluginId: 'interaction',
    managementNote: '当前机器人场景不使用执行中交互，保持关闭。',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'automation_create',
    title: '创建自动化任务',
    category: 'builtin',
    description: '在当前房间按自然语言时间创建一次性或周期性自动化任务。',
    compatibility: 'compatible',
    compatibilityNote: '只应暴露给标准 Agent 回复链路，不应在自动化执行链里再次开放。',
    hardDependencies: [],
    relatedTools: ['automation_list', 'automation_update', 'automation_pause', 'automation_resume', 'automation_delete'],
    riskLevel: 'medium',
    source: 'project',
    pluginId: 'automation',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'automation_list',
    title: '查看自动化任务',
    category: 'builtin',
    description: '查看当前房间内由当前用户创建的自动化任务。',
    compatibility: 'compatible',
    compatibilityNote: '只应暴露给标准 Agent 回复链路，不应在自动化执行链里再次开放。',
    hardDependencies: [],
    relatedTools: ['automation_create', 'automation_update', 'automation_pause', 'automation_resume', 'automation_delete'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'automation',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'automation_update',
    title: '修改自动化任务',
    category: 'builtin',
    description: '按自然语言时间修改当前房间内自动化任务的时间、目标或提醒方式。',
    compatibility: 'compatible',
    compatibilityNote: '只应暴露给标准 Agent 回复链路，不应在自动化执行链里再次开放。',
    hardDependencies: [],
    relatedTools: ['automation_list', 'automation_create', 'automation_pause', 'automation_resume', 'automation_delete'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'automation',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'automation_pause',
    title: '暂停自动化任务',
    category: 'builtin',
    description: '暂停当前房间内的自动化任务。',
    compatibility: 'compatible',
    compatibilityNote: '只应暴露给标准 Agent 回复链路，不应在自动化执行链里再次开放。',
    hardDependencies: [],
    relatedTools: ['automation_list', 'automation_update', 'automation_resume', 'automation_delete'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'automation',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'automation_resume',
    title: '恢复自动化任务',
    category: 'builtin',
    description: '恢复当前房间内已暂停的自动化任务。',
    compatibility: 'compatible',
    compatibilityNote: '只应暴露给标准 Agent 回复链路，不应在自动化执行链里再次开放。',
    hardDependencies: [],
    relatedTools: ['automation_list', 'automation_update', 'automation_pause', 'automation_delete'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'automation',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'automation_delete',
    title: '删除自动化任务',
    category: 'builtin',
    description: '删除当前房间内的自动化任务。',
    compatibility: 'compatible',
    compatibilityNote: '只应暴露给标准 Agent 回复链路，不应在自动化执行链里再次开放。',
    hardDependencies: [],
    relatedTools: ['automation_list', 'automation_update', 'automation_pause', 'automation_resume'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'automation',
  }),
  buildCatalogEntry({
    toolName: 'realtime_message_history',
    title: '查看实时消息缓存',
    category: 'builtin',
    description: '查看当前群聊里尚未注入主链路会话历史的实时消息缓存。',
    compatibility: 'compatible',
    compatibilityNote: '只读工具，用于让 reply 主链路按需查看当前群的被动消息缓存。',
    hardDependencies: [],
    relatedTools: [],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'memory_search',
    title: '记忆检索',
    category: 'builtin',
    description: '按需检索已经通过权限、归因和完整性校验的长期记忆。',
    compatibility: 'compatible',
    compatibilityNote: '主 Agent 与自动化可用；运行时会硬拒绝所有 Sub-Agent 调用。',
    hardDependencies: [],
    relatedTools: [],
    riskLevel: 'low',
    source: 'project',
  }),
  buildAgentOnlyCatalogEntry({
    toolName: 'qqbot_attachment_replay',
    title: '回放附件引用',
    category: 'builtin',
    description: '按附件引用标识回放当前会话里已归档的图片、PDF 或文件，用于按需恢复多模态输入。',
    compatibility: 'compatible',
    compatibilityNote: '仅应在标准 Agent 回复链路中按需触发，不应默认自动回灌历史原件。',
    hardDependencies: [],
    relatedTools: ['realtime_message_history'],
    riskLevel: 'medium',
    source: 'project',
    pluginId: 'workspace',
  }),
  buildAgentOnlyDisabledCatalogEntry({
    toolName: 'skill',
    title: '激活技能',
    category: 'builtin',
    description: '按名称加载已注入的 ChatLuna skill 指令集，为后续回复补充专门工作流。',
    compatibility: 'conditional',
    compatibilityNote: '这是 Agent 自身的技能装载入口，默认关闭，只有明确需要时才应放行。',
    hardDependencies: [],
    relatedTools: ['agentcli'],
    riskLevel: 'medium',
    source: 'chatluna_runtime',
    visibility: 'internal',
  }),
  buildAgentOnlyDisabledCatalogEntry({
    toolName: 'agentcli',
    title: 'Agent 配置命令',
    category: 'builtin',
    description: '执行 ChatLuna agentcli 管理命令，读取或修改 Agent 的技能、子代理与工具配置。',
    compatibility: 'incompatible',
    compatibilityNote: '这是高风险的 Agent 内部管理入口，默认关闭，不应在普通 qqbot 回复链路中暴露。',
    hardDependencies: [],
    relatedTools: ['skill'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    visibility: 'internal',
  }),
  buildAgentOnlyLockedCatalogEntry({
    toolName: 'task',
    title: 'Sub-Agent Task',
    category: 'builtin',
    description: '启动、查看或继续 Sub-Agent 任务。',
    compatibility: 'incompatible',
    compatibilityNote: '当前产品阶段关闭 Sub-Agents。',
    hardDependencies: [],
    relatedTools: [],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    visibility: 'internal',
    managementNote: 'Sub-Agents 暂时关闭，Main Agent 不允许调用 task。',
  }),
  buildAgentOnlyLockedCatalogEntry({
    toolName: 'hbu_jw_course_guidance_context',
    title: '河北大学选课指导上下文',
    category: 'builtin',
    description: '查询当前绑定用户的实时培养方案、完成进度、当前选课与完成度卡片。',
    compatibility: 'incompatible',
    compatibilityNote: '选课指导由纯命令链路执行。',
    hardDependencies: [],
    relatedTools: ['hbu_jw_course_offerings', 'hbu_jw_validate_course_recommendation'],
    riskLevel: 'medium',
    source: 'project',
    pluginId: 'hbu-course-guidance',
    managementNote: '纯命令触发能力，不允许 Agent 调用。',
  }),
  buildAgentOnlyLockedCatalogEntry({
    toolName: 'hbu_jw_course_offerings',
    title: '河北大学实时开课',
    category: 'builtin',
    description: '查询当前选课轮次中经过服务端过滤的实时可选班次。',
    compatibility: 'incompatible',
    compatibilityNote: '选课指导由纯命令链路执行。',
    hardDependencies: [],
    relatedTools: ['hbu_jw_course_guidance_context', 'hbu_jw_validate_course_recommendation'],
    riskLevel: 'medium',
    source: 'project',
    pluginId: 'hbu-course-guidance',
    managementNote: '纯命令触发能力，不允许 Agent 调用。',
  }),
  buildAgentOnlyLockedCatalogEntry({
    toolName: 'hbu_jw_validate_course_recommendation',
    title: '河北大学选课推荐验证',
    category: 'builtin',
    description: '重新查询余量和选课结果，验证推荐班次及预计方案完成度。',
    compatibility: 'incompatible',
    compatibilityNote: '选课指导由纯命令链路执行。',
    hardDependencies: [],
    relatedTools: ['hbu_jw_course_guidance_context', 'hbu_jw_course_offerings'],
    riskLevel: 'medium',
    source: 'project',
    pluginId: 'hbu-course-guidance',
    managementNote: '纯命令触发能力，不允许 Agent 调用。',
  }),
  buildLockedCatalogEntry({
    toolName: 'cf_user_profile',
    title: 'Codeforces 用户分数卡',
    category: 'web',
    description: '查询 Codeforces 用户资料、rating、rank、做题统计，并返回带头像的分数卡图片。',
    compatibility: 'incompatible',
    compatibilityNote: '已确定迁移为纯命令触发。',
    hardDependencies: [],
    relatedTools: ['cf_user_rating', 'cf_user_submissions', 'cf_contests'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'codeforces',
    managementNote: '已确定迁移为纯命令触发，Agent 调用保持关闭。',
  }),
  buildLockedCatalogEntry({
    toolName: 'cf_user_rating',
    title: 'Codeforces Rating 历史图',
    category: 'web',
    description: '查询 Codeforces 用户 rating 历史，并返回带节点分数标注的曲线图。',
    compatibility: 'incompatible',
    compatibilityNote: '已确定迁移为纯命令触发。',
    hardDependencies: [],
    relatedTools: ['cf_user_profile', 'cf_user_submissions', 'cf_contests'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'codeforces',
    managementNote: '已确定迁移为纯命令触发，Agent 调用保持关闭。',
  }),
  buildLockedCatalogEntry({
    toolName: 'cf_user_submissions',
    title: 'Codeforces 最近提交',
    category: 'web',
    description: '查询 Codeforces 用户最近提交记录、题号、 verdict 和提交时间。',
    compatibility: 'incompatible',
    compatibilityNote: '已确定迁移为纯命令触发。',
    hardDependencies: [],
    relatedTools: ['cf_user_profile', 'cf_user_rating', 'cf_contests'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'codeforces',
    managementNote: '已确定迁移为纯命令触发，Agent 调用保持关闭。',
  }),
  buildLockedCatalogEntry({
    toolName: 'cf_contests',
    title: 'Codeforces 比赛列表',
    category: 'web',
    description: '查询 Codeforces 即将开始、正在进行或最近结束的比赛。',
    compatibility: 'incompatible',
    compatibilityNote: '已确定迁移为纯命令触发。',
    hardDependencies: [],
    relatedTools: ['cf_user_profile', 'cf_user_rating', 'cf_user_submissions'],
    riskLevel: 'low',
    source: 'project',
    pluginId: 'codeforces',
    managementNote: '已确定迁移为纯命令触发，Agent 调用保持关闭。',
  }),
  buildCatalogEntry({
    toolName: 'file_read',
    title: '读取文件',
    category: 'file',
    description: '读取磁盘上的文件内容。',
    compatibility: 'incompatible',
    compatibilityNote: '宿主机文件读取能力，启用后模型可直接读取本机文件。',
    hardDependencies: [],
    relatedTools: ['file_write', 'file_edit', 'grep', 'glob', 'bash'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'file_write',
    title: '写入文件',
    category: 'file',
    description: '新建或覆盖写入单个文件。',
    compatibility: 'incompatible',
    compatibilityNote: '宿主机文件写入能力，启用后模型可直接修改本机文件。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_edit', 'file_publish', 'bash'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'file_edit',
    title: '编辑文件',
    category: 'file',
    description: '按匹配片段更新现有文件内容。',
    compatibility: 'incompatible',
    compatibilityNote: '宿主机文件编辑能力，启用后模型可对本机文件做定向修改。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_write', 'file_publish', 'bash'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'file_publish',
    title: '发布文件',
    category: 'file',
    description: '发布本地文件并生成可访问的文件链接或产物引用。',
    compatibility: 'incompatible',
    compatibilityNote: '宿主机文件发布能力，启用后模型可将本地文件作为外部可访问产物暴露。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_write', 'file_edit'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'grep',
    title: '检索文件内容',
    category: 'file',
    description: '按正则或关键字在文件中搜索匹配内容。',
    compatibility: 'incompatible',
    compatibilityNote: '宿主机文件检索能力，启用后模型可直接扫描本机文件内容。',
    hardDependencies: [],
    relatedTools: ['file_read', 'glob', 'bash'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'glob',
    title: '匹配文件路径',
    category: 'file',
    description: '按 glob 规则匹配文件路径。',
    compatibility: 'incompatible',
    compatibilityNote: '宿主机文件发现能力，启用后模型可遍历并匹配本机路径。',
    hardDependencies: [],
    relatedTools: ['file_read', 'grep', 'bash'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'bash',
    title: '执行 Bash 命令',
    category: 'file',
    description: '在宿主机本地 shell 中执行命令并返回标准输出/错误。',
    compatibility: 'incompatible',
    compatibilityNote: '这是宿主机高权限命令执行能力，当前配置下可联网且不需要审批。',
    hardDependencies: [],
    relatedTools: ['file_read', 'file_write', 'file_edit', 'grep', 'glob'],
    riskLevel: 'high',
    source: 'chatluna_runtime',
    pluginId: 'workspace',
  }),
  buildCatalogEntry({
    toolName: 'web_run',
    title: '统一 Web 访问',
    category: 'web',
    description: '统一执行搜索、图片、网页读取、链接点击、正文查找、PDF 截图和天气查询。',
    compatibility: 'compatible',
    compatibilityNote: '只读 Web capability 入口，返回可追溯的结构化 artifact 与引用。',
    hardDependencies: [],
    relatedTools: [],
    riskLevel: 'medium',
    source: 'chatluna_runtime',
    pluginId: 'web',
  }),
];

export const TOOL_CATALOG_MAP = new Map(TOOL_CATALOG.map((entry) => [entry.toolName, entry]));
